export const ChannelEvents = {
    VOTE_UPDATE: 'VOTE_UPDATE',
    USER_JOINED: 'USER_JOINED',
    TOGGLE_RESULTS: 'TOGGLE_RESULTS',
    CHANGE_VOTE: 'CHANGE_VOTE',
    LANDING_VOTE_UPDATE: 'LANDING_VOTE_UPDATE',
} as const;
